### ISSUE TITLE
Why is the hit rate low for Windows?

### ISSUE THREAD

**Issue by arBmind** [cristianadam/ccache#5]
### Question ###

On Windows builds of QtCreator the cache hit rate is very low?

On a Qt Creator compile run for a release that builds the same sources as the previous build, we get the following cache hit rates:
* Windows: 44% (https://github.com/arBmind/qt-creator/runs/4489356778?check_suite_focus=true#step:14:31)
* Linux: 81% (https://github.com/arBmind/qt-creator/runs/4489356803?check_suite_focus=true#step:14:31)
* MacOS: 90% (https://github.com/arBmind/qt-creator/runs/4489356827?check_suite_focus=true#step:14:31)

Windows seems very low here. I wonder why that is the case.

**Comment by cristianadam** [comment]
No idea. At https://github.com/qt-creator/qt-creator/actions I see 95% for MSVC jobs, which is what I would expect from a job that doesn't change much.

**Comment by arBmind** [comment]
That's more like what I would expect of it. Seems very strange.
